src/actions.js, src/constants.js, src/index.js, src/pages/Roles.js, src/reducer.js, src/translations/en.json
Implements changes requested in https://openimis.atlassian.net/browse/OFS-248
=> OFS-248: Searching for Roles

src/actions.js, src/components/RoleHeadPanel.js, src/components/RoleRightsPanel.js, src/constants.js, src/index.js, src/pages/Role.js, src/pages/Roles.js, src/reducer.js, src/translations/en.json
https://openimis.atlassian.net/browse/OFS-249
=> OFS-249: Creating a Role

src/actions.js, src/constants.js, src/pages/Roles.js, src/reducer.js, src/translations/en.json
https://openimis.atlassian.net/browse/OFS-251
=> OFS-251: Deleting a Role

src/actions.js, src/components/RoleHeadPanel.js, src/components/RoleRightsPanel.js, src/constants.js, src/index.js, src/pages/Role.js, src/pages/Roles.js, src/reducer.js, src/translations/en.json
https://openimis.atlassian.net/browse/OFS-250
=> OFS-250: Updating a Role

src/components/RoleRightsPanel.js, src/pages/Role.js
https://openimis.atlassian.net/browse/OFS-252
=> OFS-252: Fix empty permission lists on Role create

src/components/generics/Searcher.js
Allows extending searcher actions with contribution points. 
Change needed for [OAI-49](https://openimis.atlassian.net/browse/OAI-49)
=> OAI-49: Seracher actions contribution point added

README.md, src/actions.js, src/components/generics/FormPanel.js, src/index.js, src/pickers/LanguagePicker.js, src/reducer.js, src/translations/en.json
Part of [OTC-289](https://openimis.atlassian.net/browse/OTC-289).
=> OTC-289: Added language picker

src/components/generics/Searcher.js
TICKET: [OTC-303](https://openimis.atlassian.net/browse/OTC-303)
=> OTC-303: Fix contribution display condition

src/components/generics/Searcher.js, src/components/generics/Table.js
* Do not change height of the header when the actions are displayed
* Use Table.fetching to display the loading state in the Table
=> Better table

src/actions.js
https://github.com/openimis/openimis-fe_js/pull/41
=> chore(Api): Remote-User header is now set using the proxy.

src/pickers/MonthPicker.js
TICKET: [OTC-681](https://openimis.atlassian.net/browse/OTC-681)
=> OTC-681: Fixed range for month picker

src/components/generics/Searcher.js, src/components/generics/SearcherExport.js, src/helpers/downloadExport.js, src/index.js, src/translations/en.json
TICKET: [OTC-734](https://openimis.atlassian.net/browse/OTC-734)
=> OTC-734: Added exporting functionality to generic searcher

README.md, src/components/inputs/ValidatedTextInput.js, src/index.js, src/styles.js
**PART OF [*LOCATION PR*](https://github.com/openimis/openimis-fe-location_js/pull/35)**
[OP-986](https://openimis.atlassian.net/browse/OP-986)
In scope of this ticket, I implemented new, generic component ValidatedTextInput, which checks the uniqueness of entered data and gives the appropriate information about it.
[OP-986]: https://openimis.atlassian.net/browse/OP-986?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> OP-986: Implementation of component ValidatedTextInput

src/components/generics/Searcher.js
[OP-1068](https://openimis.atlassian.net/browse/OP-1068)
Changes:
- Enhancement of the pagination statuses and parameters in Searcher (missing _last_ parameter)
[OP-1068]: https://openimis.atlassian.net/browse/OP-1068?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> OP-1068: Searcher pagination fix

src/actions.js, src/components/RoleHeadPanel.js, src/pages/Role.js, src/reducer.js
https://openimis.atlassian.net/browse/OP-1082
This PR changes TextInput in role name to ValidatedTextInput. It also provides queries and hooks to fetch validated data.
It is connected with pull request on backend: https://github.com/openimis/openimis-be-core_py/pull/145
=> OP-1082: create frontend logic to validate unique role name

src/components/inputs/ValidatedTextInput.js
[OP-1062](https://openimis.atlassian.net/browse/OP-1062)
In scope of this ticket, I reverted the change I made in previous solution. To be more precised, I removed the additional clearAction - it was dusturbing other validations.
[OP-1062]: https://openimis.atlassian.net/browse/OP-1062?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> OP-1062: Removal of additional clearAction

src/reducer.js
Added while working on [OTC-790](https://openimis.atlassian.net/browse/OTC-790) [(Location PR)](https://github.com/openimis/openimis-fe-location_js/pull/40). 
Additional state cleaning on logout added . 
[OTC-790]: https://openimis.atlassian.net/browse/OTC-790?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> OTC-790: State cleanup on logout

src/pages/Role.js
https://openimis.atlassian.net/browse/OTC-966
=> OTC-966: make save button always visible

src/components/inputs/NumberInput.js
https://openimis.atlassian.net/browse/OP-1310
This PR adds a prop that allows to use decimals in number input.
Related to: https://github.com/openimis/openimis-fe-claim_js/pull/85
=> OP-1310: add decimal prop to number input

README.md, src/actions.js, src/components/App.js, src/components/generics/ConstantBasedPicker.js, src/components/generics/Form.js, src/components/generics/Searcher.js, src/components/generics/Table.js, src/components/inputs/Autocomplete.js, src/components/inputs/NumberInput.js, src/components/inputs/TextInput.js, src/components/inputs/ValidatedTextInput.js, src/constants.js, src/index.js, src/pages/LoginPage.js, src/pages/Role.js, src/pages/Roles.js, src/pickers/MonthPicker.js, src/pickers/YearPicker.js, src/reducer.js, src/translations/en.json
MERGING RELEASE branches
Release release/23.04
=> MERGING RELEASE branches

src/helpers/utils.js, src/pages/Role.js
[OP-1331](https://openimis.atlassian.net/browse/OP-1331)
Changes:
- Button will stay disabled if no changes were made in Role management form.
[OP-1331]: https://openimis.atlassian.net/browse/OP-1331?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> OP-1331: Do not allow to save if no change

src/pages/Role.js
[OP-1417](https://openimis.atlassian.net/browse/OP-1417)
Changes:
- No possibility to edit/save again Role instantly after first save.
- Added lockedPage styles to the form after save.
[OP-1417]: https://openimis.atlassian.net/browse/OP-1417?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> OP-1417: Block editing/saving after first Role save

src/components/generics/Searcher.js
https://openimis.atlassian.net/browse/OP-1341
After this PR filtering will be taking back to first page.
=> OP-1341: when change pages and filtering go to page 0

src/components/inputs/Autocomplete.js
**RELATED TO [FE PRODUCT PR](https://github.com/openimis/openimis-fe-product_js/pull/53)**
[OTC-1037](https://openimis.atlassian.net/browse/OTC-1037)
Changes:
- Allow to live access the search string.
[OTC-1037]: https://openimis.atlassian.net/browse/OTC-1037?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> OTC-1037: Live access to searchString

src/pages/Roles.js
[OTC-1088](https://openimis.atlassian.net/browse/OTC-1088)
Changes:
- The functionality for clearing the search criterias when clicking "Reset" button fixed.
[OTC-1088]: https://openimis.atlassian.net/browse/OTC-1088?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> OTC-1088: fix resetting search criteria in rights management panel

src/components/inputs/ValidatedTextAreaInput.js, src/index.js
https://openimis.atlassian.net/browse/CM-28
It is also a part of:
https://github.com/openimis/openimis-be-social_protection_py/pull/3
https://github.com/openimis/openimis-fe-social_protection_js/pull/3
=> CM-28: add ValidatedTextAreaInput

src/components/generics/Searcher.js
https://openimis.atlassian.net/browse/CM-105
When using cache default filters were not fetched once changed. Changing default filters fill result in filtering.
=> CM-105: fetch when default filters change

README.md, src/constants.js, src/helpers/json-handler-utils.js, src/index.js
[RELATED PR](https://github.com/openimis/openimis-fe-social_protection_js/pull/20)
[CM-110](https://openimis.atlassian.net/browse/CM-110)
Changes:
- Created _json-handler-utils_ to handle JSON parsing and rendering JSX components based on that.
[CM-110]: https://openimis.atlassian.net/browse/CM-110?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> CM-110: create a util for handling json input, attach docs

src/components/generics/Searcher.js
Reverts openimis/openimis-fe-core_js#125
=> Revert "CM-105: fetch when default filters change"

src/actions.js, src/components/generics/Searcher.js, src/reducer.js
https://openimis.atlassian.net/browse/CM-108
This PR adds ability to reset filters on when searcher unmounts.
=> CM-108: add ability to reset filters on unmount

src/components/generics/Searcher.js
https://openimis.atlassian.net/browse/OTC-1116
Changes:
- OrderBy name fixed
- Fixes broken claim module
=> OTC-1116: Searcher filter fix.

README.md, src/components/RequireAuth.js
TICKET: [CM-213](https://openimis.atlassian.net/browse/CM-213)
[CM-213]: https://openimis.atlassian.net/browse/CM-213?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> CM-213: Added configurable draver menu

README.md, src/components/RequireAuth.js
Ticket: https://openimis.atlassian.net/jira/software/c/projects/ONI/issues/ONI-126
Changes:
- Changed default setting
- Added docs for calendar setting.
=> ONI-126: Default calendar setting changed. Docs added.

src/reducer.js
https://openimis.atlassian.net/browse/CM-204
This PR fixes journalization caused by bug in redux state.
=> CM-204: fix redux state

src/index.js
TICKET: https://openimis.atlassian.net/browse/CM-209
=> CM-209: added some compoments to exports

src/helpers/utils.js
Ticket: https://openimis.atlassian.net/browse/ONI-64
Connected PR's:
https://github.com/openimis/openimis-fe_js/pull/95
https://github.com/openimis/openimis-fe-claim_js/pull/113
Changes:
- Added utils to calculate time difference between two days in days.
- Additional util to calculate difference between current day and other picked day.
=> ONI-64: Added utils to calculate time difference in days.

src/index.js, src/reports/RegistersStatusReport.js, src/translations/en.json
[Ticket](https://openimis.atlassian.net/jira/software/c/projects/OMT/issues/OMT-323)
[BE PR](https://github.com/openimis/openimis-be-core_py/pull/207)
=> OMT-323 - Registers Status report

src/components/generics/Form.js, src/helpers/i18n.js
https://openimis.atlassian.net/browse/OP-781
This PR adjust Form to display multiple Fab Tooltips.
Related to: 
https://github.com/openimis/openimis-fe-claim_js/pull/128
=> OP-781: adjust form to displaying multiple fab tooltips

src/actions.js, src/components/JournalDrawer.js, src/constants.js
https://openimis.atlassian.net/browse/OP-1328
This PR adds claim submission stats to the journal drawer.
It needs: https://github.com/openimis/openimis-be-claim_py/pull/131
=> OP-1328: add claim submission stats

src/pickers/DatePicker.js
https://openimis.atlassian.net/browse/OP-1527
This PR fixes switching between nepali and general calendar.
Wait until this one is merged: https://github.com/openimis/openimis-fe-claim_js/pull/134
=> OP-1527: fix nepali calendar

src/components/generics/Table.js
https://openimis.atlassian.net/browse/OP-1540
This PR takes into account pagination when calculating ordinal number.
=> OP-1540: ordinal number takes into account pagination

src/components/JournalDrawer.js
[OP-1486](https://openimis.atlassian.net/browse/OP-1486)
Changes:
- Prevent site crashing if mutation details were in incorrect format.
[OP-1486]: https://openimis.atlassian.net/browse/OP-1486?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> OP-1486: fix error handling in journal drawer

src/components/dialogs/AdvancedFiltersDialog.js, src/components/generics/Searcher.js, src/components/generics/SearcherPane.js
https://openimis.atlassian.net/browse/CM-296
This PR adds additional params to custom filter request.
It needs: https://github.com/openimis/openimis-be-core_py/pull/218
=> CM-296: add additional params to custom filters

src/components/generics/Table.js
Ticket: https://openimis.atlassian.net/browse/ONI-143
Changes:
- Changed function to calculate serial numbers
- Now tables with paginations are supported
- Prettified whole file
=> ONI-143: Added serial numbers to tables with pagination.

src/components/LogoutButton.js, src/constants.js, src/pages/LoginPage.js
https://openimis.atlassian.net/browse/OM-66
Key for config fe-core on front: "LogoutButton.showMPassProvider"
=> OM-66: add config to logout using mpass

src/components/LogoutButton.js
fixing issue with the logout
https://openimis.atlassian.net/browse/OM-66
=> OM-66: remove imis logout

README.md, src/components/LogoutButton.js, src/constants.js, src/helpers/utils.js, src/pages/LoginPage.js
https://openimis.atlassian.net/browse/OM-66
=> OM-66: move mPass redirect to the utils

src/components/App.js, src/components/LogoutButton.js, src/constants.js
https://openimis.atlassian.net/browse/OM-70
It needs: https://github.com/openimis/openimis-be-core_py/pull/230
=> OM-70: get user roles

src/components/LogoutButton.js, src/helpers/utils.js
This PR adds clearing local storage on saml logout. Also it creates dispatcher instance on logout.
=> hotfix-saml-logout: clear local storage on logout

src/components/App.js
This PR fixes logic connected to opening eu modal.
=> hotfix-eu-button: fix logic in useEffect

src/components/inputs/Autocomplete.js
[OP-1625](https://openimis.atlassian.net/browse/OP-1625)
Changes:
- Delete selecting if length === 1. It was causing issues.
[OP-1625]: https://openimis.atlassian.net/browse/OP-1625?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> OP-1625: remove auto select

src/components/generics/Form.js
Ticket: https://openimis.atlassian.net/browse/OP-1663
Connected PR: https://github.com/openimis/openimis-fe-claim_js/pull/163
Changes:
- Added openDirty value to fab button.
=> OP-1663: Fetch openDirty value in fab button.

src/actions.js, src/components/dialogs/ExportColumnsDialog.js, src/components/generics/Searcher.js, src/components/generics/SearcherExport.js, src/reducer.js, src/translations/en.json
https://openimis.atlassian.net/browse/CM-359
This PR adds modal that allows to choose columns to export and updates searcher to make it work.
=> CM-359: add choose exported columns modal

src/components/dialogs/ExportColumnsDialog.js, src/components/generics/Searcher.js, src/components/generics/SearcherExport.js
https://openimis.atlassian.net/browse/CM-359
=> CM-359: update export components to be able to choose fields from schema

src/components/App.js, src/components/RequireAuth.js
[ONI-149](https://openimis.atlassian.net/browse/ONI-149)
Changes:
- Maintain the status of the calendar toggle switch.
- Clicking the main IMIS logo navigates to the homepage without reloading the site.
[ONI-149]: https://openimis.atlassian.net/browse/ONI-149?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ONI-149: preserve calendar switch state

src/components/generics/ConstantBasedPicker.js, src/components/inputs/SelectInput.js
[ONI-185](https://openimis.atlassian.net/browse/ONI-185)
Changes:
- Remove marginTop if label is not visible.
[ONI-185]: https://openimis.atlassian.net/browse/ONI-185?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ONI-185: generic component styling fixes

src/components/generics/WarningBox.js, src/index.js
[OP-1824](https://openimis.atlassian.net/browse/OP-1824)
[RELATED](https://github.com/openimis/openimis-fe-contribution_js/pull/41)
Changes:
- Customizable Box which allows to display some information to the end user.
[OP-1824]: https://openimis.atlassian.net/browse/OP-1824?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> OP-1824: add warning box

src/pickers/DatePicker.js
[OP-1818](https://openimis.atlassian.net/browse/OP-1818)
Changes:
- Fix _minDate_, _maxDate_ and _disablePast_ within DatePicker component. 
[OP-1818]: https://openimis.atlassian.net/browse/OP-1818?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> OP-1818: min/max date fix

src/helpers/i18n.js, src/pickers/NeDateFormatter.js, src/translations/en.json
[OP-1838](https://openimis.atlassian.net/browse/OP-1838)
Changes:
- Display fallback if date does not fall within proper date range.
- Lokalise key has been added.
[OP-1838]: https://openimis.atlassian.net/browse/OP-1838?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> OP-1838: add placeholder if date does not fall within proper date range

src/components/inputs/NumberInput.js
[OP-1814](https://openimis.atlassian.net/browse/OP-1814)
https://github.com/openimis/openimis-fe-contribution_js/pull/42
https://github.com/openimis/openimis-fe-product_js/pull/84
Changes:
- Display 0 in number input if displayZero true and value === 0.
[OP-1814]: https://openimis.atlassian.net/browse/OP-1814?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> OP-1814: display 0 if value equals 0 in number input

src/pickers/DatePicker.js
Add _minDate_ and _maxDate_ to the MUIDatePicker component.
=> hotfix: fix min/max date

src/components/generics/SearcherPane.js
[OP-1848](https://openimis.atlassian.net/browse/OP-1848)
https://github.com/openimis/openimis-fe_js/pull/124
Changes:
- Improve the clarity of action buttons in searcher.
[OP-1848]: https://openimis.atlassian.net/browse/OP-1848?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> OP-1848: improve clarity of action buttons in searcher

src/components/generics/SearcherPane.js
=> fix: fix search function

src/components/generics/Searcher.js, src/components/generics/SearcherPane.js, src/pickers/DatePicker.js
MERGING develop into release/24.04
=> MERGING develop into release/24.04

src/components/RoleRightsPanel.js, src/translations/en.json
[OP-1853](https://openimis.atlassian.net/browse/OP-1853)
Changes:
- Add possibility to select all (filtered) perms. If no filter, add all.
- Add possibility to remove all (filtered) perms. If no filter, remove all.
[OP-1853]: https://openimis.atlassian.net/browse/OP-1853?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> OP-1853: add possibility to add/remove all perms

src/components/App.js, src/pickers/CustomFilterFieldStatusPicker.js
https://openimis.atlassian.net/browse/CM-854
It needs: https://github.com/openimis/openimis-fe-grievance_social_protection_js/pull/2
=> CM-854: add grievance config modal

src/actions.js, src/pages/LoginPage.js
Ticket: https://openimis.atlassian.net/browse/CQI-153
Changes:
- error is fetched to get proper messaged according to the raised error
=> CQI-153: login lockout mechanism

src/actions.js
Ticket:
https://openimis.atlassian.net/browse/CQI-159
Changes:
- XCSRF-Token is added to login request to allow backend middleware validating value
- there is an option to add custom headers
How was it tested?
1. Login works.
2. Login request intercepted and with modified csrf token does not work.
3. Other requests don't have XCSRF-Token token and they work as before.
=> Feature/cqi 159: XCSRF-Token added to login request

src/actions.js, src/helpers/passwordValidator.js, src/index.js, src/pages/SetPasswordPage.js, src/reducer.js
Ticket:
https://openimis.atlassian.net/browse/CQI-169
Changes:
- added password validator for reset password functionality
Note:
- fe-core witll store those validators, fe-admin will be changed to use imported from fe-core
=> CQI-169: added password validator for reset password functionality
