src/components/RoleHeadPanel.js

https://openimis.atlassian.net/browse/OFS-287

OFS-287: Disable System checkbox

---

src/pages/LoginPage.js

TICKET: https://openimis.atlassian.net/browse/OSD-182
part of TICKET: https://openimis.atlassian.net/browse/OP-785
RELATED PR: https://github.com/openimis/openimis-fe_js/pull/63
After this change it should look like below:
the logo from demo to compare:

OSD-182: resize logo after adding new one on assembly

---

src/components/generics/Table.js

Additional functionality allowing functions as headers. 
Part of [OP-835](https://openimis.atlassian.net/browse/OP-835)

OP-835: Extend table for functional headers

---

src/actions.js

[https://openimis.atlassian.net/browse/OTC-748](https://openimis.atlassian.net/browse/OTC-748)
Changes:
- Added an option to overrige default `/api` backend root with a custom one with `REACT_APP_API_URL`. This is done at build time and cannot be updated at runtime.

OTC-748 Added support for custom api url

---

src/components/generics/ConstantBasedPicker.js

https://openimis.atlassian.net/browse/OP-1078
This PR not only does resolve the issue in the case mentioned in the ticket, but also should make every picker work fine when choosing option: **ANY**.

OP-1072: parse undefined value of a picker to null

---

src/components/inputs/ValidatedTextInput.js
src/constants.js

PART OF [MEDICAL_PRICELIST PR](https://github.com/openimis/openimis-fe-medical_pricelist_js/pull/26)
In scope of this ticket, I made slight changes to the ValidatedTextInput component. To be more precise, I changed the way how debounce works. It allows me to implement the validation of pricelist name and moreover it fixed the issue when you paste a name into the input and undo it (previously sometimes it crashed and it did not update the state properly).

OP-981: ValidatedTextInput fix, adding constant

---

src/components/inputs/ValidatedTextInput.js

Part of [POLICY PR](https://github.com/openimis/openimis-fe-policy_js/pull/27)
Part of [CONTRIBUTION PR](https://github.com/openimis/openimis-fe-contribution_js/pull/7)
In scope of this PR, I implemented the possibility to pass more than one argument as a query identifier. Currently, we can pass as many arguments as we need, it is enough to put them into _additionalQueryArgs_ object.

OP-1037: Adding possibility to enter more than 1 arg to query

---

src/components/inputs/ValidatedTextInput.js

Part of [LOCATION PR](https://github.com/openimis/openimis-fe-location_js/pull/37)
In scope of this ticket, I implemented the possibility to use _autoFocus_ prop, which allows to focus on code field when location dialog appears. Moreover, I added one additional invoke of clearAction to avoid the conflict with input styles.

OP-1062: autoFocus implemented, additional invoke of clearAction

---

src/components/inputs/ValidatedTextInput.js

Part of [LOCATION PR](https://github.com/openimis/openimis-fe-location_js/pull/38)
[OTC-883](https://openimis.atlassian.net/browse/OTC-883)
In scope of this ticket, I created new prop which allow us to fix blinking input styles and it will help us to fix the issue with disabled save buttons during first edit.
[OTC-883]: https://openimis.atlassian.net/browse/OTC-883?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OTC-883: implementation of setValidAction

---

src/actions.js
src/components/RoleHeadPanel.js
src/reducer.js

[OTC-884](https://openimis.atlassian.net/browse/OTC-884)
In scope of this ticket, I corrected the state of isValid by adding an extra action, which sets the state properly when we're editing a name of role for the first time. Moreover, there was an issue when we paste an invalid role name and then revert it using CTRL+Z to the valid one, save button was anyway blocked although saving should be possbile. After the fix, it works as intended.
[OTC-884]: https://openimis.atlassian.net/browse/OTC-884?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OTC-884: Disabled save button in role management fix

---

src/components/inputs/TextInput.js
src/components/inputs/ValidatedTextInput.js

[OTC-873](https://openimis.atlassian.net/browse/OTC-873)
RELATED [ADMIN PR](https://github.com/openimis/openimis-fe-admin_js/pull/49)
In scope of this ticket, I added the possibility to pass a prop _type_. While working on this, I also fixed readOnly property. Now, it blocks the validation field after save.
[OTC-873]: https://openimis.atlassian.net/browse/OTC-873?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OTC-873: Adding type prop, readOnly fix

---

README.md
src/components/dialogs/SelectDialog.js
src/index.js

RELATED [POLICY PR](https://github.com/openimis/openimis-fe-policy_js/pull/32)
[OTC-786](https://openimis.atlassian.net/browse/OTC-786)
In scope of this ticket:
- Implementation of the generic _SelectDialog_ - the pop up dialog to display a message and take some simple action after it. It is not using Redux store and actions. Moreover, it is fully editable - button labels, message content and title might be modified through the props.
- README has been updated - I added the description about _SelectDialog_.
[OTC-786]: https://openimis.atlassian.net/browse/OTC-786?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OTC-786: SelectDialog implementation

---

src/components/RoleHeadPanel.js
src/pickers/LanguagePicker.js

[OTC-925](https://openimis.atlassian.net/browse/OTC-925)
Changes:
- Removal of unsed imports in _LanguagePicker.js_.
- Circular dependency fix - _ValidatedTextInput.js_ has to be imported from "@openimis/fe-core" - it was imported from "../index".
[OTC-925]: https://openimis.atlassian.net/browse/OTC-925?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OTC-925: Circular dependency fix, removal of unused imports

---

src/actions.js
src/components/generics/Searcher.js
src/constants.js
src/index.js
src/pages/Roles.js
src/reducer.js

[OTC-757](https://openimis.atlassian.net/browse/OTC-757)
Changes:
- New actions and reducers to control the pagination through the Redux store.
- Saving information like current page, cursors and current module in the Redux store.
- Clearing pagination state if entered the Roles page.
- Implementation of the logic responsible for going back from edit form and keeping the same page which was before.
[OTC-757]: https://openimis.atlassian.net/browse/OTC-757?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OTC-757: Searcher feature, clearing pagination if enetered the Roles

---

README.md
src/components/App.js
src/pages/LoginPage.js

This change allow registering routing for views that don't require user authentication (e.g. self registration form) and making contributions directly to the LoginPage.

Contribution key for unregistered routing and login page

---

src/components/inputs/Autocomplete.js

**[POLICY PR](https://github.com/openimis/openimis-fe-policy_js/pull/42) AND [PRODUCT PR](https://github.com/openimis/openimis-fe-product_js/pull/43) REQUIRED**
[OTC-1037](https://openimis.atlassian.net/browse/OTC-1037)
Changes:
- I changed _renderInput_ into conditional rendering. It allows to use _renderInputs_ straight from the component.
[OTC-1037]: https://openimis.atlassian.net/browse/OTC-1037?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OTC-1037: Conditional rendering of renderInput

---

src/components/generics/ConstantBasedPicker.js

https://openimis.atlassian.net/browse/CM-107
I fixed withLabel funcionality in the scope of above ticket. Now if withLabel false it will display no label. It used to display "false".
It has to be " " instead of "" because it somehow throws an error. " " in terms of displaying it should not be a problem to have space as something inside quotationmarks.

CM-107: if withLabel false display nothing

---

src/pickers/YearPicker.js

Allow to set the YearPicker as a readOnly field.

hotfix: add readOnly props to the YearPicker

---

src/components/inputs/NumberInput.js
src/components/inputs/TextInput.js

[OP-1481](https://openimis.atlassian.net/browse/OP-1481)
Changes:
- Change number input type to "number". Previously, there was a "tel" type which was causing some issues with resetting field when typing letters.
- Hide the increment/decrement arrows from the number input.
Demo:
(After typing '123', I'm trying to enter letters - it is not possible and it does not clear the input)
[OP-1481]: https://openimis.atlassian.net/browse/OP-1481?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OP-1481: change type of number input, hide up/down arrow keys

---

src/components/RequireAuth.js
src/components/generics/Searcher.js
src/helpers/i18n.js
src/pickers/DatePicker.js
src/pickers/NeDateFormatter.js
src/translations/en.json

Ticket: https://openimis.atlassian.net/browse/ONI-125
Changes:
- Added translation key for calendar switcher
- Added calendar switch to localStorage
- It is used to change type of date displayed in the search results.

ONI-125: Cookie for calendar type added. Date display added for all searches.

---

src/components/inputs/Autocomplete.js

[OP-1536](https://openimis.atlassian.net/browse/OP-1536)
[RELATED PR](https://github.com/openimis/openimis-fe-product_js/pull/62)
[RELATED PR](https://github.com/openimis/openimis-fe-policy_js/pull/58)
Changes:
- If only 1 option available in options, select this option. This feature applies to dropdowns that utilize Autocomplete under the hood. AutoSuggestion continues to function as it did prior to this change.
Officer Picker - Autocomplete component - only 1 officer available and it's selected once user enters the form: ![image](https://github.com/openimis/openimis-fe-core_js/assets/109145288/f0fdf0c0-18c3-4f09-a50e-c2d6eccbcdda)
Note: I've implemented this in a generic component, and it currently only functions for dropdowns that are marked as required. However, there are situations …

OP-1536: autoselect option if only 1 available

---

src/components/inputs/SelectInput.js

[OP-1726](https://openimis.atlassian.net/browse/OP-1726)
Changes:
- Integrate a "Clear" button into the SelectInput component.
Functionality details:
The "Clear" button remains hidden when no option is selected in the SelectInput component.
Once an option is selected, the "Clear" button becomes visible, allowing the user to easily deselect the chosen option.
[OP-1726]: https://openimis.atlassian.net/browse/OP-1726?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OP-1726: add clear button to the selectinput component

---

src/components/generics/Table.js

[ONI-134](https://openimis.atlassian.net/browse/ONI-134)
[RELATED PR](https://github.com/openimis/openimis-fe-claim_js/pull/171)
Changes:
- Add an _extendHeader_ prop to enhance the Table component's header with additional information provided by the parent component.
[ONI-134]: https://openimis.atlassian.net/browse/ONI-134?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ONI-134: allow to extend table header

---

README.md
src/components/App.js
src/components/ErrorPage.js
src/components/ForbiddenPage.js
src/components/InternalServerErrorPage.js
src/components/NotFoundPage.js
src/components/PermissionCheck.js
src/helpers/ErrorBoundary.js
src/translations/en.json

[OP-1747](https://openimis.atlassian.net/browse/OP-1747)
Changes:
- Develop and integrate a variety of error pages (401, 404, 500).
- Enhance the "core.Router" contribution by introducing a new property, **requiredRights**. This feature will manage access permissions to resources, ensuring that unauthorized access attempts are met with an error message and a subsequent redirection to an appropriate error page.
- Update Lokalise keys.
Summary:
1. Access is automatically allowed if **requiredRights** is undefined.
2. Access is universally denied and an error page displayed if **requiredRights** is an empty array.
3. When **requiredRights** is specified with necessary rights, access is conditionally granted based on permission validation.
[OP-1747]: …

OP-1747: create 401 403 500 error pages and extend right/error handling

---

src/components/inputs/NumberInput.js

[OP-1630](https://openimis.atlassian.net/browse/OP-1630)
[RELATED PR](https://github.com/openimis/openimis-fe-product_js/pull/82)
Changes:
- Introduce a _allowDecimals_ variable to manage whether the number input should permit decimal values. This variable acts as a switch to enable or disable the acceptance of decimals in the input field.
- If _allowDecimals_ is false, user is not able to enter a floating point. By default, it is set to true.
[OP-1630]: https://openimis.atlassian.net/browse/OP-1630?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OP-1630: add variable to control input value

---

src/components/RequireAuth.js
src/components/generics/MainMenuContribution.js
src/components/generics/Searcher.js
src/constants.js
src/pages/LoginPage.js

[OM-115](https://openimis.atlassian.net/browse/OM-115)
[REQUIRED PR](https://github.com/openimis/openimis-fe_js/pull/114)
Changes:
- Make _MainMenuContribution_ styles more flexible.
- Adjust logo rendering.
[OM-115]: https://openimis.atlassian.net/browse/OM-115?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OM-115: fix sidebar, layout adjustments

---

src/components/inputs/Autocomplete.js

[OP-1759](https://openimis.atlassian.net/browse/OP-1759)
[RELATED PR](https://github.com/openimis/openimis-fe-claim_js/pull/175)
Changes:
- Allow Autocomplete value to be empty.
[OP-1759]: https://openimis.atlassian.net/browse/OP-1759?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OP-1759: allow value to be empty

---

src/components/generics/Table.js

[OP-1790](https://openimis.atlassian.net/browse/OP-1790)
[RELATED PR](https://github.com/openimis/openimis-fe-policy_js/pull/84)
Changes:
- If formatter function is null, return null (do not return a cell).
[OP-1790]: https://openimis.atlassian.net/browse/OP-1790?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OP-1790: add possibility to hide cell if formatter is null

---

src/components/generics/Table.js

[OP-1829](https://openimis.atlassian.net/browse/OP-1829)
[RELATED](https://github.com/openimis/openimis-fe-claim_js/pull/180)
Changes:
- If _disableDeleteOnEmptyRow_ is true, disable the delete button on empty row.
[OP-1829]: https://openimis.atlassian.net/browse/OP-1829?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OP-1829: add possibility to disable delete button

---

src/components/inputs/AmountInput.js

[OP-1830](https://openimis.atlassian.net/browse/OP-1830)
[RELATED](https://github.com/openimis/openimis-fe-claim_js/pull/181)
Changes:
- Set min value to 0 by default.
- Added possibility to change the min value.
- If value is set to negative, there is an error: 
[OP-1830]: https://openimis.atlassian.net/browse/OP-1830?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OP-1830: enable changing min value of amount input - default 0

---

src/components/generics/Searcher.js

Hotfix: 
- Disable fetching on every filters change. Now user has to change a filter and click on the Search button.

hotfix: do not fetch instantly on filters change

---

src/components/RoleRightsPanel.js
src/helpers/role-label-formatter.js
src/index.js
src/pages/Roles.js
src/pickers/AuthorityPicker.js
src/translations/en.json

[OP-1825](https://openimis.atlassian.net/browse/OP-1825)
[BE PR](https://github.com/openimis/openimis-be-core_py/pull/277)
Changes:
- Integrate the role right label format.
- Add Authority picker to extend filters.
[OP-1825]: https://openimis.atlassian.net/browse/OP-1825?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OP-1825: add filter on role by authority

---

src/components/App.js
src/components/generics/FatalError.js
src/translations/en.json

Ticket:
https://openimis.atlassian.net/browse/CQI-156
Changes:
- fatal error page is now using ErrorPage component
- there is different message based on the status.code returned
How was it tested?
1. For rate limit error it worked as intended
Note:
Fatal error page should not include return button for now, it would create an issue where user is blocked because he tried to spam application so he won't be able to use the button if he reached the limit.

CQI-156: added fatal error page for rate limit
